pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'rikorose/gcc-cmake'
                }
            }
            steps {
				sh 'rm -r src/build/*'
				sh 'cd src/build && cmake .. '
				sh 'cd src/build && make'
				sh './src/build/tutorial'
            }
        }
    }
}
