pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'rikorose/gcc-cmake'
                }
            }
            steps {
				sh 'mkdir src/build'
				sh 'cd src/build && cmake .. '
				sh 'cd src/build && make'
            }
        }
    }
}
