pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'rikorose/gcc-cmake bash'
                }
            }
            steps {
				sh 'cmake .. '
				sh 'make'
            }
        }
    }
}
